-- ============================================================
-- Tabela: v_vendedores_integracao
-- Descrição: Mapeamento de vendedores TOTVS → ClickUp/Evolution
-- Atualizado em: 2025-04-19 (adicionado Jucelino - totvs_id 288)
-- ============================================================

CREATE TABLE IF NOT EXISTS v_vendedores_integracao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  totvs_id INTEGER NOT NULL,
  nome_vendedor TEXT NOT NULL,
  modulo TEXT, -- 'multimarcas', 'revenda', 'business', 'varejo', 'franquia'
  ativo BOOLEAN DEFAULT TRUE,
  clickup_id TEXT,
  evolution_id UUID,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_vendedores_totvs_id ON v_vendedores_integracao(totvs_id);
CREATE INDEX IF NOT EXISTS idx_vendedores_modulo ON v_vendedores_integracao(modulo);
CREATE INDEX IF NOT EXISTS idx_vendedores_ativo ON v_vendedores_integracao(ativo);

-- RLS (Row Level Security)
ALTER TABLE v_vendedores_integracao ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leitura pública vendedores" ON v_vendedores_integracao
  FOR SELECT USING (true);

CREATE POLICY "Escrita admin vendedores" ON v_vendedores_integracao
  FOR ALL USING (
    auth.jwt() ->> 'role' IN ('owner', 'admin')
  );

-- ============================================================
-- SEED: Vendedores cadastrados (dados do TOTVS em 2025-04-19)
-- ============================================================

-- === MULTIMARCAS ===
INSERT INTO v_vendedores_integracao (totvs_id, nome_vendedor, modulo, ativo, clickup_id, evolution_id)
VALUES
  (21,  'Rafael',  'multimarcas', true, 'd8398e05-78e5-4227-8152-18a06295e365', 'c93c3ef9-e703-4f26-8694-fb4c5f4dad9a'),
  (26,  'David',   'multimarcas', true, 'eecbe9b3-a7e1-468c-acd7-bddb8519f817', '6c23d656-18f0-4f25-ae92-2ec5ac57741e'),
  (65,  'Renato',  'multimarcas', true, '36122170-bc21-4c42-ba38-69578d3f2669', NULL),
  (69,  'Thalis',  'multimarcas', true, '1d8ea8ac-0f37-4d7e-8bba-b0330e95951b', NULL),
  (177, 'Walter',  'multimarcas', true, '8d9005ed-c880-4bd7-8d83-99e67567b7b3', NULL),
  (259, 'Arthur',  'multimarcas', true, 'a29d039c-d3a9-4f5f-acb8-014196255b87', '33d3f748-11f9-4454-8717-5bafb2924a45')
ON CONFLICT DO NOTHING;

-- === REVENDA ===
INSERT INTO v_vendedores_integracao (totvs_id, nome_vendedor, modulo, ativo, clickup_id, evolution_id)
VALUES
  (15,  'Heyridan', 'revenda', true, 'b89da272-1d7c-409a-ba81-4f81113d7a93', '08460f28-d3fb-41c0-8445-98c4e795b6e5'),
  (25,  'Anderson', 'revenda', true, '6eaa04c7-93e7-4caf-8eec-43662d9e86d8', '72e47e69-b68d-415e-a6bd-95dbf6e5e7d1'),
  (161, 'Cleiton',  'revenda', true, '972010b0-8cd6-4d58-b7a5-3c790252fa5f', '434a351c-98d2-4e6b-bb9d-865e5dce6e49'),
  (165, 'Michel',   'revenda', true, 'e702004a-19cc-4df0-9c82-e3099a0d8e47', 'd29b496e-f65a-4c2e-899c-39ae3696717a'),
  (241, 'Yago',     'revenda', true, '3c3bbcf5-a670-4618-b08a-0fd11db36d91', '84300f8b-83e8-4a58-9b2b-a20979e5f639'),
  (251, 'Felipe',   'revenda', true, '0124a178-34c0-4721-b518-bd7e15310ed1', '65a7a939-67a2-4f35-94e9-d97c6b76e4c6'),
  (288, 'Jucelino', 'revenda', true, NULL, NULL)
ON CONFLICT DO NOTHING;

-- === BUSINESS ===
INSERT INTO v_vendedores_integracao (totvs_id, nome_vendedor, modulo, ativo, clickup_id, evolution_id)
VALUES
  (20, 'Marcio', 'business', true, '2e269255-f10f-406f-82c5-88ebd9f8c2be', '0413e067-9e13-4991-a564-8247cb6ea5d6')
ON CONFLICT DO NOTHING;
