const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(
  'https://dorztqiunewggydvkjnf.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvcnp0cWl1bmV3Z2d5ZHZram5mIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzA3MTI4OCwiZXhwIjoyMDYyNjQ3Mjg4fQ.sk6z1v-MKAjiQK-IfIvPvxI-GdRyH_Biaj5a-8_Ksy8'
);

const dados = [
  { empresa: 'Crosby brejinho', transacao: '929', fornecedor: 'FRANCINALDO G DE SOUZA', nfe: '929', valor: 5166.75, data_lancamento: '2026-06-05', status: 'Pago', data_pagamento: '2026-06-05', forma: 'Cartao', cartao_conta: 'NUBANK SARA', parcelas: 10, valor_pago: 5809.25, observacao: 'Diferenca de pagamento ref. ao juros - conciliado', tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '843810/ 846036/ 559555', fornecedor: 'J L DA LIMA CANDIDO', nfe: '386', valor: 13772.00, data_lancamento: null, status: 'Parcial', data_pagamento: '2026-06-05', forma: 'PIX', cartao_conta: 'STONE - 1007', parcelas: null, valor_pago: 10000.00, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '?', fornecedor: 'CAMISARIA ARREMATE COMERCIO', nfe: '19268', valor: 2490.00, data_lancamento: '2026-06-09', status: 'Pago', data_pagamento: '2026-06-08', forma: 'PIX', cartao_conta: 'SIDREDI - CROSBY', parcelas: null, valor_pago: 2490.00, observacao: 'Pago junto duas nfe 19270 e 19268', tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '?', fornecedor: 'CAMISARIA ARREMATE COMERCIO', nfe: '19270', valor: 3955.00, data_lancamento: '2026-06-09', status: 'Pago', data_pagamento: '2026-06-08', forma: 'PIX', cartao_conta: 'SIDREDI - CROSBY', parcelas: null, valor_pago: 3955.00, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '845871', fornecedor: '2A CONFECCOES LTDA', nfe: '219', valor: 1852.50, data_lancamento: '2026-06-02', status: 'Pago', data_pagamento: '2026-06-11', forma: 'Cartao', cartao_conta: 'SICREDI - 0115', parcelas: 10, valor_pago: 1054.00, observacao: 'Pagamento feito parte em cartao e parte em pix, diferenca do valor da nota e ref. ao juros da maquineta - conciliado', tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '845874', fornecedor: '2A CONFECCOES LTDA', nfe: '219', valor: 76.00, data_lancamento: '2026-06-02', status: 'Pago', data_pagamento: '2026-06-11', forma: 'PIX', cartao_conta: 'STONE - 1007', parcelas: null, valor_pago: 991.07, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '850640', fornecedor: 'F E K FACCAO LTDA', nfe: '9279', valor: 647.40, data_lancamento: '2026-06-11', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '850784', fornecedor: 'F E K FACCAO LTDA', nfe: '9279', valor: 581.40, data_lancamento: '2026-06-11', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '850846', fornecedor: 'F E K FACCAO LTDA', nfe: '9279', valor: 15.00, data_lancamento: '2026-06-12', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '850835', fornecedor: 'F E K FACCAO LTDA', nfe: '9279', valor: 1435.00, data_lancamento: '2026-06-12', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '849477', fornecedor: '2A CONFECCOES LTDA', nfe: '220', valor: 2517.50, data_lancamento: '2026-06-10', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '852781', fornecedor: '2A CONFECCOES LTDA', nfe: '221', valor: 143.00, data_lancamento: '2026-06-15', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '852786', fornecedor: '2A CONFECCOES LTDA', nfe: '221', valor: 1534.00, data_lancamento: '2026-06-15', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '853591', fornecedor: 'F E K FACCAO LTDA', nfe: '9279', valor: 866.40, data_lancamento: '2026-06-16', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '853675', fornecedor: 'F E K FACCAO LTDA', nfe: '9279', valor: 38.00, data_lancamento: '2026-06-17', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '854199', fornecedor: 'J L DA LIMA CANDIDO', nfe: null, valor: 8850.00, data_lancamento: '2026-06-18', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: false, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '854208', fornecedor: '2A CONFECCOES LTDA', nfe: '223', valor: 3296.50, data_lancamento: '2026-06-18', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '856277', fornecedor: 'F E K FACCAO LTDA', nfe: null, valor: 555.00, data_lancamento: '2026-06-23', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: false, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '829487', fornecedor: 'AELSON - 2A', nfe: '213', valor: 1624.50, data_lancamento: '2026-04-24', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '819584', fornecedor: 'AELSON - 2A', nfe: '210', valor: 2156.50, data_lancamento: '2026-03-30', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '823568', fornecedor: 'AELSON - 2A', nfe: '211', valor: 2137.50, data_lancamento: '2026-04-09', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '823573', fornecedor: 'AELSON - 2A', nfe: '211', valor: 9.50, data_lancamento: '2026-04-09', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: '825167', fornecedor: 'AELSON - 2A', nfe: '212', valor: 1157.00, data_lancamento: '2026-04-13', status: 'Pendente', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: true },
  { empresa: 'Crosby brejinho', transacao: null, fornecedor: 'OCKER - FIO FINO', nfe: '1427', valor: null, data_lancamento: null, status: 'Aguardando Nota', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: false },
  { empresa: 'Crosby brejinho', transacao: null, fornecedor: 'OCKER - FIO FINO', nfe: '1431', valor: null, data_lancamento: null, status: 'Aguardando Nota', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: false },
  { empresa: 'Crosby brejinho', transacao: null, fornecedor: 'OCKER - FIO FINO', nfe: '1389', valor: null, data_lancamento: null, status: 'Aguardando Nota', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: false },
  { empresa: 'Crosby brejinho', transacao: null, fornecedor: 'LENIVALDO - BERMUDAS, SHORTS E CALCAS', nfe: '384', valor: null, data_lancamento: null, status: 'Aguardando Nota', data_pagamento: null, forma: null, cartao_conta: null, parcelas: null, valor_pago: null, observacao: null, tem_nota: true, tem_transacao: false },
];

async function main() {
  const { data, error } = await supabase.from('pagamentos_fabricas').insert(dados).select('id');
  if (error) {
    console.error('ERRO:', error.message);
  } else {
    console.log('Inseridos ' + data.length + ' registros com sucesso!');
  }
}
main();
